image: cypress/base:10

pipelines:
  custom:
    manual:
      - step:
          script:
            # install dependencies
            - npm install
            # run Cypress tests
            - npm run cy:run:boohoo:dashboard
          artifacts:
            # store any generates images and videos as artifacts
            - cypress/screenshots/**
            - cypress/videos/**