type AddressMap = Record<string, Record<'primaryAddress' | 'secondaryAddress' | 'newAddedPrimaryAddress', AddressData>>

class Addresses {
  
  public addressMap: AddressMap = {
    UK: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UK1',
        month: 'May',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '02075906960',
        addressLine: '259 Oxford Street',
        postcode: 'S6 3FD',
        addressName: 'SecondaryAddress',
        country: 'United Kingdom',
        city: 'Sheffield',
        countryCode: 'GB',
        county: 'South Yorkshire',
        addressNickname: 'UK2',
        month: 'May',
      },
      newAddedPrimaryAddress:{
        firstName: 'BoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'NewUK',
        month: 'May',
      }
    },

    // United States addresses.
    US: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '19176409576',
        addressLine: '1665 St Marks Ave',
        postcode: '11233',
        addressName: 'PrimaryAddress',
        country: 'United States',
        city: 'New York',
        countryCode: 'US',
        county: 'Alabama',
        addressNickname: 'US1',
        month: 'May',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '12122733267',
        addressLine: '110 W 15th St',
        postcode: '45202-7008',
        addressName: 'SecondaryAddress',
        country: 'United States',
        city: 'Cincinnati',
        countryCode: 'US',
        county: 'New York',
        addressNickname: 'US2',
        month: 'May',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '19176409576',
        addressLine: '1665 St Marks Ave',
        postcode: '11233',
        addressName: 'PrimaryAddress',
        country: 'United States',
        city: 'New York',
        countryCode: 'US',
        county: 'Alabama',
        addressNickname: 'NewUS',
        month: 'May',
      }
    },

    // Ireland addresses.
    IE: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '35314850900',
        addressLine: '32 Marlfield Mall',
        postcode: 'D24 YT57',
        addressName: 'PrimaryAddress',
        country: 'Ireland',
        city: 'Dublin 24',
        countryCode: 'IE',
        county: 'Dublin',
        addressNickname: 'IE1',
        month: 'May',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '35316615133',
        addressLine: '10 Blackhall Green, Arbour Hill',
        postcode: 'D07 EK13',
        addressName: 'SecondaryAddress',
        country: 'Ireland',
        city: 'Dublin 7',
        countryCode: 'IE',
        county: 'Dublin',
        addressNickname: 'IE2',
        month: 'May',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '35314850900',
        addressLine: '32 Marlfield Mall',
        postcode: 'D24 YT57',
        addressName: 'PrimaryAddress',
        country: 'Ireland',
        city: 'Dublin 24',
        countryCode: 'IE',
        county: 'Dublin',
        addressNickname: 'IE3',
        month: 'May',
      }
    },

    // Germany addresses.
    DE: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '306948868',
        addressLine: 'Potsdamer Str. 50',
        postcode: '10785',
        addressName: 'PrimaryAddress',
        country: 'Deutschland',
        city: 'Berlin',
        countryCode: 'DE',
        county: 'Berlin',
        addressNickname: 'DE1',
        month: 'Mai',
        
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '1631161055',
        addressLine: 'Schleiermacherstr. 18',
        postcode: '51377',
        addressName: 'SecondaryAddress',
        country: 'Deutschland',
        city: 'Leverkusen',
        countryCode: 'DE',
        county: 'Leverkusen',
        addressNickname: 'DE2',
        month: 'Mai',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '306948348',
        addressLine: 'Auguststraße 68',
        postcode: '10117',
        addressName: 'PrimaryAddress',
        country: 'Deutschland',
        city: 'Berlin',
        countryCode: 'DE',
        county: 'Berlin',
        addressNickname: 'DENew',
        month: 'Mai',
      }
    },

    // France addresses.
    FR: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '142223144',
        addressLine: '132 Rue de Rennes',
        postcode: '75006',
        addressName: 'PrimaryAddress',
        country: 'France',
        city: 'Paris',
        countryCode: 'FR',
        county: '',
        addressNickname: 'FR1',
        month: 'Mai',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '140750875',
        addressLine: '75Bis Avenue Marceau',
        postcode: '75116',
        addressName: 'SecondaryAddress',
        country: 'France',
        city: 'Paris',
        countryCode: 'FR',
        county: 'Paris',
        addressNickname: 'FR2',
        month: 'Mai',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: '75116',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'Paris',
        countryCode: 'FR',
        county: 'Paris',
        addressNickname: 'FRNew',
        month: 'Mai',
      }
    },

    // Italy addresses.
    IT: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '0642440415',
        addressLine: 'Via del Corso, 98 ',
        postcode: '00187',
        addressName: 'PrimaryAddress',
        country: 'Italia',
        city: 'Roma',
        countryCode: 'IT',
        county: '',
        addressNickname: 'IT1',
        month: 'Maggio',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '0648124524',
        addressLine: 'Viale delle Provincie 31',
        postcode: '00162',
        addressName: 'SecondaryAddress',
        country: 'Italia',
        city: 'Roma',
        countryCode: 'IT',
        county: 'RM',
        addressNickname: 'IT2',
        month: 'Maggio',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'Maggio',
      }
    },

    // Spain addresses.
    ES: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '34932160306',
        addressLine: 'Passeig de Gràcia, 43',
        postcode: '08007',
        addressName: 'PrimaryAddress',
        country: 'España',
        city: 'Barcelona',
        countryCode: 'ES',
        county: '',
        addressNickname: 'ES1',
        month: 'Mayo',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '34935537801',
        addressLine: 'Avinguda Diagonal, 208',
        postcode: '08018',
        addressName: 'SecondaryAddress',
        country: 'España',
        city: 'Barcelona',
        countryCode: 'ES',
        county: 'Barcelona',
        addressNickname: 'ES2',
        month: 'Mayo',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'Mayo',
      }
    },

    // Canada addresses.
    CA: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '19053547887',
        addressLine: '6361 Fallsview Blvd, Niagara Falls',
        postcode: 'L2G 3V9',
        addressName: 'PrimaryAddress',
        country: 'Canada',
        city: 'Niagra Falls',
        countryCode: 'CA',
        county: '',
        addressNickname: 'CA1',
        month: 'May',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '6135550114',
        addressLine: '75 Rue Ontario E',
        postcode: 'H2X 1G9',
        addressName: 'SecondaryAddress',
        country: 'Canada',
        city: 'Montréal',
        countryCode: 'CA',
        county: 'Quebec',
        addressNickname: 'CA2',
        month: 'May',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'May',
      }
    },

    // Israel addresses.
    IL: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '4792540835',
        addressLine: 'HaMaccabi 2',
        postcode: '6329302',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'Tel Aviv',
        countryCode: 'IL',
        county: 'Israel',
        addressNickname: 'IL1',
        month: 'מאי',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '972558829936',
        addressLine: 'Ramban St 30',
        postcode: '	9270007',
        addressName: 'SecondaryAddress',
        country: 'Israel',
        city: 'Jerusalem',
        countryCode: 'IL',
        county: 'Jerusalem',
        addressNickname: 'IL2',
        month: 'מאי',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'מאי',
      }
    },

    // Finland addresses.
    FI: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '358294500501',
        addressLine: 'Mannerheiminaukio 2',
        postcode: '00100',
        addressName: 'PrimaryAddress',
        country: 'Finland',
        city: 'Helsinki',
        countryCode: 'FI',
        county: '',
        addressNickname: 'FI1',
        month: 'Toukokuu',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '358409109222',
        addressLine: 'Rauhankatu 29',
        postcode: '20100',
        addressName: 'SecondaryAddress',
        country: 'Finland',
        city: 'Turku',
        countryCode: 'FI',
        county: '',
        addressNickname: 'FI2',
        month: 'Toukokuu',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'Toukokuu',
      }
    },

    // Netherlands addresses.
    NL: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '31689124321',
        addressLine: 'Museumstraat 1',
        postcode: '1071 XX',
        addressName: 'PrimaryAddress',
        country: 'Nederland',
        city: 'Amsterdam',
        countryCode: 'NL',
        county: '',
        addressNickname: 'NL1',
        month: 'Mei',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '31689124321',
        addressLine: 'Jaffadwarsstraat 20A',
        postcode: '3061 JS',
        addressName: 'SecondaryAddress',
        country: 'Nederland',
        city: 'Rotterdam',
        countryCode: 'NL',
        county: '',
        addressNickname: 'NL2',
        month: 'Mei',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '31689124321',
        addressLine: 'Museumstraat 1',
        postcode: '1071 XX',
        addressName: 'PrimaryAddress',
        country: 'Nederland',
        city: 'Amsterdam',
        countryCode: 'NL',
        county: '',
        addressNickname: 'NL3',
        month: 'Mei',
      }
    },

    // Sweden addresses.
    SE: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '+46701740615',
        addressLine: 'Torsgatan 10',
        postcode: '111 23',
        addressName: 'PrimaryAddress',
        country: 'Sverige',
        city: 'Stockholm',
        countryCode: 'SE',
        county: '',
        addressNickname: 'SE1',
        month: 'Maj',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '+46701740615',
        addressLine: 'Stadsgårdshamnen 22',
        postcode: '116 45',
        addressName: 'SecondaryAddress',
        country: 'Sverige',
        city: 'Stockholm',
        countryCode: 'SE',
        county: '',
        addressNickname: 'SE2',
        month: 'Maj',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '+46701740615',
        addressLine: 'Torsgatan 10',
        postcode: '111 23',
        addressName: 'PrimaryAddress',
        country: 'Sverige',
        city: 'Stockholm',
        countryCode: 'SE',
        county: '',
        addressNickname: 'SE3',
        month: 'Maj',
      }
    },

    // Norway addresses.
    NO: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '4721982000',
        addressLine: 'Universitetsgata 13',
        postcode: '0164',
        addressName: 'PrimaryAddress',
        country: 'Norway',
        city: 'Oslo',
        countryCode: 'NO',
        county: '',
        addressNickname: 'NO1',
        month: 'Mai',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '4721982000',
        addressLine: 'Akersbakken 39',
        postcode: '0172',
        addressName: 'SecondaryAddress',
        country: 'Norway',
        city: 'Oslo',
        countryCode: 'NO',
        county: '',
        addressNickname: 'NO2',
        month: 'Mai',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '4721982000',
        addressLine: 'Universitetsgata 13',
        postcode: '0164',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'Norway',
        countryCode: 'Oslo',
        county: 'NO',
        addressNickname: 'NO3',
        month: 'Mai',
      }
    },
    
    // Denmark addresses.
    DK: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '4538163816',
        addressLine: 'Nordre Fasanvej 57',
        postcode: '2000',
        addressName: 'PrimaryAddress',
        country: 'Denmark',
        city: 'Frederiksberg',
        countryCode: 'DK',
        county: '',
        addressNickname: 'DK1',
        month: 'Maj',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '4570232110',
        addressLine: 'Vandkunsten 5',
        postcode: '1467',
        addressName: 'SecondaryAddress',
        country: 'Denmark',
        city: 'København K',
        countryCode: 'DK',
        county: '',
        addressNickname: 'DK2',
        month: 'Maj',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '08082580300',
        addressLine: '85 Piccadilly',
        postcode: 'W1J 7NB',
        addressName: 'PrimaryAddress',
        country: 'United Kingdom',
        city: 'London',
        countryCode: 'GB',
        county: 'London',
        addressNickname: 'UKNew',
        month: 'Maj',
      }
    },

    // Australia addresses.
    AU: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '292475630',
        addressLine: '50 Clunies Ross St, Australian Capital Territory',
        postcode: '2600',
        addressName: 'PrimaryAddress',
        country: 'Australia',
        city: 'Sydney',
        countryCode: 'AU',
        county: 'ACT',
        addressNickname: 'AU1',
        month: '',
        
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '0491570156',
        addressLine: '10 Legon Rd',
        postcode: '3167',
        addressName: 'SecondaryAddress',
        country: 'Australia',
        city: 'Oakleigh South',
        countryCode: 'AU',
        county: 'Oakleigh South',
        addressNickname: 'AU2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '292475630',
        addressLine: '50 Clunies Ross St, Australian Capital Territory',
        postcode: '3167',
        addressName: 'PrimaryAddress',
        country: 'Australia',
        city: 'Sydney',
        countryCode: 'AU',
        county: 'ACT',
        addressNickname: 'AU3',
        month: '',
      }
    },

    // New Zealand addresses.
    NZ: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '6433456789 ',
        addressLine: '123 Pinehaven Road',
        postcode: '5019',
        addressName: 'PrimaryAddress',
        country: '',
        city: 'Pinehaven',
        countryCode: 'NZ',
        county: 'Upper Hutt',
        addressNickname: 'NZ1',
        month: '',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '34351201',
        addressLine: '12 Central Road',
        postcode: '1021',
        addressName: 'SecondaryAddress',
        country: 'New Zealand',
        city: 'Auckland',
        countryCode: 'NZ',
        county: 'Kingsland',
        addressNickname: 'NZ2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '64231531376',
        addressLine: 'Mount Wellington Highway',
        postcode: '1060',
        addressName: 'PrimaryAddress',
        country: 'New Zealand',
        city: 'Auckland',
        countryCode: 'NZ',
        county: 'Kingsland',
        addressNickname: 'NZ3',
        month: '',
      }
    },

    // European Union addresses.
    EU: {
      primaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '05776795095',
        addressLine: 'Karlsplatz 8',
        postcode: '1040',
        addressName: 'PrimaryAddress',
        country: 'Austria',
        city: 'Wien',
        countryCode: 'AT',
        county: '',
        addressNickname: 'AT1',
        month: '',
      },
      secondaryAddress:  {
        firstName: 'New',
        lastName: 'Test',
        phone: '05776795095',
        addressLine: 'Oberntalweg 4',
        postcode: '6080',
        addressName: 'SecondaryAddress',
        country: 'Austria',
        city: 'Innsbruck',
        countryCode: 'AT',
        county: '',
        addressNickname: 'AT2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '05776795095',
        addressLine: 'Karlsplatz 8',
        postcode: '1040',
        addressName: 'PrimaryAddress',
        country: 'Austria',
        city: 'Wien',
        countryCode: 'AT',
        county: '',
        addressNickname: 'NewAT1',
        month: '',
      }
    },

    // Saudi Arabia addresses.
    SA: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '5014245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Saudi Arabia',
        city: 'Jeddah',
        countryCode: 'SA',
        county: 'Eastern Province',
        addressNickname: 'SA1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Saudi Arabia',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'SA2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Saudi Arabia',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'SA3',
        month: '',
      }
    },

    // UAE addresses
    AE: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '5014245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'UAE',
        city: 'Hatta',
        countryCode: 'AE',
        county: 'Ajman',
        addressNickname: 'AE1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'UAE',
        city: 'Riyadh',
        countryCode: 'AE',
        county: 'Riyadh Province',
        addressNickname: 'AE2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'UAE',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'AE3',
        month: '',
      }
    },

    // Bahrain addresses
    BH: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '3314245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Bahrain',
        city: 'Diraz',
        countryCode: 'BH',
        county: 'Southern',
        addressNickname: 'BH1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Bahrain',
        city: 'Riyadh',
        countryCode: 'BH',
        county: 'Riyadh Province',
        addressNickname: 'BH2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Bahrain',
        city: 'Riyadh',
        countryCode: 'BA',
        county: 'Riyadh Province',
        addressNickname: 'BA3',
        month: '',
      }
    },

    // Jordan addresses
    JO: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '7914245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Jordan',
        city: 'Rabba',
        countryCode: 'JO',
        county: 'Mafraq Governorate',
        addressNickname: 'JO1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Jordan',
        city: 'Riyadh',
        countryCode: 'JO',
        county: 'Riyadh Province',
        addressNickname: 'JO2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Jordan',
        city: 'Riyadh',
        countryCode: 'JO',
        county: 'Riyadh Province',
        addressNickname: 'JO3',
        month: '',
      }
    },

    // Kuwait addresses
    KW: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '5614245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Kuwait',
        city: 'Jibla',
        countryCode: 'KW',
        county: 'Hawalli Governorate',
        addressNickname: 'KW1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Kuwait',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'KW2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Kuwait',
        city: 'Riyadh',
        countryCode: 'KW',
        county: 'Riyadh Province',
        addressNickname: 'KW3',
        month: '',
      }
    },

    // Bahrain addresses
    OM: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '9314245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Oman',
        city: 'Barka',
        countryCode: 'OM',
        county: 'Dhofar Governorate',
        addressNickname: 'OM1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Oman',
        city: 'Riyadh',
        countryCode: 'OM',
        county: 'Riyadh Province',
        addressNickname: 'OM2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Oman',
        city: 'Riyadh',
        countryCode: 'OM',
        county: 'Riyadh Province',
        addressNickname: 'OM3',
        month: '',
      }
    },

    // Qatar addresses
    QA: {
      primaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '5514245353',
        addressLine: 'Unit: A2, King Abdul Aziz Rd',
        postcode: '12467',
        addressName: 'PrimaryAddress',
        country: 'Qatar',
        city: 'Baaya',
        countryCode: 'SA',
        county: 'Al Khor',
        addressNickname: 'QA1',
        month: '',
      },
      secondaryAddress: {
        firstName: 'New',
        lastName: 'Test',
        phone: '567960904',
        addressLine: '2873 Al Khudair',
        postcode: '6259',
        addressName: 'SecondaryAddress',
        country: 'Qatar',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'QA2',
        month: '',
      },
      newAddedPrimaryAddress:{
        firstName: 'ZBoohooNew',
        lastName: 'Test',
        phone: '5679609042',
        addressLine: '33, Bareed Dist.',
        postcode: '1623',
        addressName: 'PrimaryAddress',
        country: 'Qatar',
        city: 'Riyadh',
        countryCode: 'SA',
        county: 'Riyadh Province',
        addressNickname: 'QA3',
        month: '',
      }
    }
  };

  /**
   * Returns an address for a locale, given it's the primary test address or secondary test address.
   * @param locale The locale given from the environment variables
   * @param type either primaryAddress or secondaryAddress 
   * @returns AddressData type with all the details for an address.
   */
  getAddressByLocale (locale: string, type: 'primaryAddress' | 'secondaryAddress' | 'newAddedPrimaryAddress'): AddressData {
    if (typeof this.addressMap[locale] === 'undefined') throw new Error('Address could not be found with locale ' + locale);
    return this.addressMap[locale][type] as AddressData;
  }

}

export default new Addresses();